<a href="https://colab.research.google.com/github/fac3lessd0ge/MTUCI_algo/blob/main/tasks/matrix_diagonal_sort14_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import numpy as np
import time

In [56]:
def sample_matrix(low = 0, high = 20, size = (20, 5)):
    return np.random.randint(low, high, size)

In [57]:
print(sample_matrix())

[[ 1 11  4 14 13]
 [ 9  2  3  2 14]
 [ 3  7 10 16 19]
 [18  9 19  2  3]
 [10  2 18 12  4]
 [11 16  3  4 19]
 [ 3 16 17  4 13]
 [19  3  8  3  0]
 [ 5 19  1 18  2]
 [19  3 16 11  9]
 [12  5  0 13  5]
 [ 9  4  4 14 16]
 [17 11 18  5  5]
 [ 6 19 18 10 14]
 [ 3 14 12 17 19]
 [17  9  3 12 12]
 [10  4  1  3  3]
 [17  6 10  8 10]
 [ 1  0  8  5  2]
 [ 6  3 10 19  4]]


In [58]:
def sort_diagonals(mat, size : tuple):
    """
    size = (width, height)
    """

    result = []

    for i in range(size[0]-1, -1, -1):
        temp = []
        y = i
        x = 0
        while y <= size[0]-1 and x <= size[1]-1:
            temp.append(mat[y][x])
            y+=1
            x+=1
        result.append(temp)

    for i in range(1, size[1]):
        temp = []
        y = 0
        x = i
        while y <= size[0]-1 and x <= size[1]-1:
            temp.append(mat[y][x])
            y+=1
            x+=1
        result.append(temp)
    
    for diag in result:
        diag.sort()
    return result


In [59]:
a = sample_matrix(size=(20,20))
print(a, '\n\n-----------------\n')

print(np.array(sort_diagonals(a, (20, 20)), dtype=object))

[[ 0  7  9 10 10 13  4 10 13 19 10 15  4 12  9  8  4 14 14  3]
 [ 5  7  9 12  9 14  9 10  7 19 14 11  0  2 11  2 19  1  6  0]
 [ 1  7  4  3 10 12 11  8 12  3  1 10  1  4 14  7  1 12 19 17]
 [ 3  2  1 19 14 15 16  6  6  5 17 17 17 17  0  6 10 17 14  4]
 [10  9  3 16  8 19  2 11 14  0  8  2 14  3 17 10 12 19 10  3]
 [ 7 12  8  8 16 17  7  3 17 19  0 17 18  4  7  4  7  8  8 16]
 [11  3  6  2 18  7 12 14  0 16 10  0 19  0 15 10 18  6 13 19]
 [ 8  8 16 15 10 19  1 14 15 15  4 18 11  5  8 16 18  0 10 10]
 [ 5 16 15  9  1 14 19  7 10  6 14  2 17  2 13 19 11  7 13 17]
 [16  3  9  6 17 14 15 17 10 11 17 19 10  6 12 14  9 12  1 16]
 [17 14  7 15 18 12  2  8 15 18 19  1 19  6 12  0 13  5 17  8]
 [ 6 19 12 16 10 10 16  3 13  4  7 12  9  0 11  5 14 11  4  1]
 [12  6 11  8 13 19 13 16  2  8 15 14  5  9 18 16  9 10  9 13]
 [ 2  1 17  8 17 12 19 17  3 16  6  7 17 10 12  9 14  5 17  1]
 [ 3  8 12  4  4  4  0  4 13  4 14 12 15 14  5  5  3  7 10  6]
 [ 1 12  8  8  1 13  5 12 18 19 17  0  6  7 14  2 15 13

In [60]:
def sort_matrix(mat, size: tuple):
    diagonals = np.array(sort_diagonals(mat, size))

    current_x = 0
    current_y = 0


    for i in range(size[0]-1, -1, -1):
        y = i
        x = 0
        while y <= size[0]-1 and x <= size[1]-1:
            mat[y][x] = diagonals[current_y][current_x]
            y+=1
            x+=1
            current_x = (current_x + 1) % (len(diagonals[current_y]))
            if current_x == 0: current_y = (current_y + 1) % (len(diagonals) + 1)



    for i in range(1, size[1]):
        y = 0
        x = i
        while y <= size[0]-1 and x <= size[1]-1:
            mat[y][x] = diagonals[current_y][current_x]
            y+=1
            x+=1
            current_x = (current_x + 1) % (len(diagonals[current_y]))
            if current_x == 0: current_y += 1

    return mat
        

In [61]:
a = sample_matrix(size=(20,20))
print(a, '\n\n-----------------\n')

print(sort_matrix(a,size =  (20, 20)), '\n\n')

[[19 17 10 13  2  8  3 14  4  5  4  1  7 15  5 11  7  5  8  4]
 [ 3 17 18 17 16  4 18 18  5  8  7 17 18  8  4  0 15  4  0  8]
 [19 11  7  8 14  4  9 12 12  5  6 18  8 12 17  5  4  6  8 16]
 [19  3  0 13  0  5  5  6  3 15 11 16 10  4 16 14  3 13  2 13]
 [ 7 10  0  5  9 11  7  8  6  7 13  6 12  4  6  6 18  2  6  2]
 [15  1  8  1  5  4 18  5 15  2 15  0  3  1 19 17  1  1 15  6]
 [ 3  6 16  9 17  7 16  6  9  5  5 13  8  2 18  4  5  6  9  6]
 [ 9  0  6  9 15 12  5  0 11 18 19 10  1  7  3  0  7  1 19  2]
 [ 1  2  2 15 18 14  0 16 12  4  6  0 13 11 18 18 16 12 18 16]
 [ 6 15 18  9  1 13 19 14 11 13 17 11 19  0 14 19  6 13 10 14]
 [ 5  1 13  1 16  9 14 13  5  3 10 10 12  3 13 17 14  4  4 10]
 [ 1 12  0  4  5 12  6  4  2  6  6  4 15  5 13 13 17 12  8  7]
 [ 4  2  3  7 16  0 18 12  0  8  3  1  6 19  4 14 16 13  7 17]
 [ 5  3 17 15 16 10  0 19 13  6 18  8 17  7 14  1 16 15 19 19]
 [11 15  1  0  2 16  8 13  8 19  9 10 10 14 10 16 13 15 10  9]
 [ 8  7 10 10 10 18 15 16 17 10 15  7  1  6  1  8 13  0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  
