<a href="https://colab.research.google.com/github/fac3lessd0ge/MTUCI_algo/blob/main/tasks/matrix_diagonal_sort14_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Условие задачи
### Дана матрица размером m * n, в которой значения - целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию, и возвращающую получившуюся матрицу.

In [55]:
import numpy as np
import time

In [56]:
def sample_matrix(low = 0, high = 20, size = (20, 5)):
    return np.random.randint(low, high, size)

In [57]:
print(sample_matrix())

[[ 1 11  4 14 13]
 [ 9  2  3  2 14]
 [ 3  7 10 16 19]
 [18  9 19  2  3]
 [10  2 18 12  4]
 [11 16  3  4 19]
 [ 3 16 17  4 13]
 [19  3  8  3  0]
 [ 5 19  1 18  2]
 [19  3 16 11  9]
 [12  5  0 13  5]
 [ 9  4  4 14 16]
 [17 11 18  5  5]
 [ 6 19 18 10 14]
 [ 3 14 12 17 19]
 [17  9  3 12 12]
 [10  4  1  3  3]
 [17  6 10  8 10]
 [ 1  0  8  5  2]
 [ 6  3 10 19  4]]


In [58]:
def sort_diagonals(mat, size : tuple):
    """
    size = (width, height)
    """

    result = []

    for i in range(size[0]-1, -1, -1):
        temp = []
        y = i
        x = 0
        while y <= size[0]-1 and x <= size[1]-1:
            temp.append(mat[y][x])
            y+=1
            x+=1
        result.append(temp)

    for i in range(1, size[1]):
        temp = []
        y = 0
        x = i
        while y <= size[0]-1 and x <= size[1]-1:
            temp.append(mat[y][x])
            y+=1
            x+=1
        result.append(temp)
    
    for diag in result:
        diag.sort()
    return result


In [59]:
a = sample_matrix(size=(20,20))
print(a, '\n\n-----------------\n')

print(np.array(sort_diagonals(a, (20, 20)), dtype=object))

[[ 0  7  9 10 10 13  4 10 13 19 10 15  4 12  9  8  4 14 14  3]
 [ 5  7  9 12  9 14  9 10  7 19 14 11  0  2 11  2 19  1  6  0]
 [ 1  7  4  3 10 12 11  8 12  3  1 10  1  4 14  7  1 12 19 17]
 [ 3  2  1 19 14 15 16  6  6  5 17 17 17 17  0  6 10 17 14  4]
 [10  9  3 16  8 19  2 11 14  0  8  2 14  3 17 10 12 19 10  3]
 [ 7 12  8  8 16 17  7  3 17 19  0 17 18  4  7  4  7  8  8 16]
 [11  3  6  2 18  7 12 14  0 16 10  0 19  0 15 10 18  6 13 19]
 [ 8  8 16 15 10 19  1 14 15 15  4 18 11  5  8 16 18  0 10 10]
 [ 5 16 15  9  1 14 19  7 10  6 14  2 17  2 13 19 11  7 13 17]
 [16  3  9  6 17 14 15 17 10 11 17 19 10  6 12 14  9 12  1 16]
 [17 14  7 15 18 12  2  8 15 18 19  1 19  6 12  0 13  5 17  8]
 [ 6 19 12 16 10 10 16  3 13  4  7 12  9  0 11  5 14 11  4  1]
 [12  6 11  8 13 19 13 16  2  8 15 14  5  9 18 16  9 10  9 13]
 [ 2  1 17  8 17 12 19 17  3 16  6  7 17 10 12  9 14  5 17  1]
 [ 3  8 12  4  4  4  0  4 13  4 14 12 15 14  5  5  3  7 10  6]
 [ 1 12  8  8  1 13  5 12 18 19 17  0  6  7 14  2 15 13

In [62]:
def sort_matrix(mat, size: tuple):
    diagonals = np.array(sort_diagonals(mat, size), dtype = object)

    current_x = 0
    current_y = 0


    for i in range(size[0]-1, -1, -1):
        y = i
        x = 0
        while y <= size[0]-1 and x <= size[1]-1:
            mat[y][x] = diagonals[current_y][current_x]
            y+=1
            x+=1
            current_x = (current_x + 1) % (len(diagonals[current_y]))
            if current_x == 0: current_y = (current_y + 1) % (len(diagonals) + 1)



    for i in range(1, size[1]):
        y = 0
        x = i
        while y <= size[0]-1 and x <= size[1]-1:
            mat[y][x] = diagonals[current_y][current_x]
            y+=1
            x+=1
            current_x = (current_x + 1) % (len(diagonals[current_y]))
            if current_x == 0: current_y += 1

    return mat
        

In [71]:
a = sample_matrix(size=(20, 20))
print('\nИсходная матрица:\n\n', a, '\n\n', 'Отсортированная матрица:\n\n', sort_matrix(a.copy(), size =  (20, 20)))


Исходная матрица:

 [[17 10 12  4 13 17  9 19  8  5  0 11 19 12  0 14 16 12  8  8]
 [15 12 12  4  8 10 18 10 16  2 13  5  0 16  0 16  3  1  0 16]
 [17 14 11  8  7  7 12 10 19 11 12 18 16 15 12  1 17 13 12 14]
 [ 8 12  5  5  1 14 15 18 17  0 14  1  9  8 12 13  3 15  1 14]
 [16 14 12 10 12  6  0 15  6  3 11 13  1 18  0  6 11  7  6 12]
 [10  6  3 17 14  1 18 15  7  6 17 18 19 14 12 12 13  1 15  0]
 [10 13 10 11 11 13 11 11 11  5  3  6  6  8 11  7 11 15 13  1]
 [18  2  1  8  7  8  7 18  6  1  2  5 18  1  5  1  1  7 17  4]
 [18 12  8 17  8 12 17 11 16 19  3  5  3  3 15  2 19  6  0  6]
 [ 6 10 17  8  6  9  3  8 12  9 14  1  9 10  6  4  3 12  5 17]
 [18 10 19 10  7  7  1 11  6  7 10 10  5 14  8 14 19  9  4  1]
 [ 1  1  9 10  9 10 13  0  5 10  7 16 16 17 11 16 15 10  6 13]
 [18  7 15  5  7 15 12  9  3  1 16 18 12 19  0 18 19 14 13  1]
 [ 1  0 10  6 13  1 16  5 10 12 15  9 12 16  9  1  3  5  4 12]
 [14  4 10  4  5  3  6 11 15 13  3 17  5  6 19  7 16  2 11 16]
 [10  0 13 16 17 12 16  8  9 11  3