<a href="https://colab.research.google.com/github/fac3lessd0ge/MTUCI_algo/blob/main/tasks/matrix_diagonal_sort14_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Условие задачи
### Дана матрица размером m * n, в которой значения - целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию, и возвращающую получившуюся матрицу.

In [55]:
import numpy as np
import time

In [56]:
def sample_matrix(low = 0, high = 20, size = (20, 5)):
    return np.random.randint(low, high, size)

In [57]:
print(sample_matrix())

[[ 1 11  4 14 13]
 [ 9  2  3  2 14]
 [ 3  7 10 16 19]
 [18  9 19  2  3]
 [10  2 18 12  4]
 [11 16  3  4 19]
 [ 3 16 17  4 13]
 [19  3  8  3  0]
 [ 5 19  1 18  2]
 [19  3 16 11  9]
 [12  5  0 13  5]
 [ 9  4  4 14 16]
 [17 11 18  5  5]
 [ 6 19 18 10 14]
 [ 3 14 12 17 19]
 [17  9  3 12 12]
 [10  4  1  3  3]
 [17  6 10  8 10]
 [ 1  0  8  5  2]
 [ 6  3 10 19  4]]


In [58]:
def sort_diagonals(mat, size : tuple):
    """
    size = (width, height)
    """

    result = []

    for i in range(size[0]-1, -1, -1):
        temp = []
        y = i
        x = 0
        while y <= size[0]-1 and x <= size[1]-1:
            temp.append(mat[y][x])
            y+=1
            x+=1
        result.append(temp)

    for i in range(1, size[1]):
        temp = []
        y = 0
        x = i
        while y <= size[0]-1 and x <= size[1]-1:
            temp.append(mat[y][x])
            y+=1
            x+=1
        result.append(temp)
    
    for diag in result:
        diag.sort()
    return result


In [59]:
a = sample_matrix(size=(20,20))
print(a, '\n\n-----------------\n')

print(np.array(sort_diagonals(a, (20, 20)), dtype=object))

[[ 0  7  9 10 10 13  4 10 13 19 10 15  4 12  9  8  4 14 14  3]
 [ 5  7  9 12  9 14  9 10  7 19 14 11  0  2 11  2 19  1  6  0]
 [ 1  7  4  3 10 12 11  8 12  3  1 10  1  4 14  7  1 12 19 17]
 [ 3  2  1 19 14 15 16  6  6  5 17 17 17 17  0  6 10 17 14  4]
 [10  9  3 16  8 19  2 11 14  0  8  2 14  3 17 10 12 19 10  3]
 [ 7 12  8  8 16 17  7  3 17 19  0 17 18  4  7  4  7  8  8 16]
 [11  3  6  2 18  7 12 14  0 16 10  0 19  0 15 10 18  6 13 19]
 [ 8  8 16 15 10 19  1 14 15 15  4 18 11  5  8 16 18  0 10 10]
 [ 5 16 15  9  1 14 19  7 10  6 14  2 17  2 13 19 11  7 13 17]
 [16  3  9  6 17 14 15 17 10 11 17 19 10  6 12 14  9 12  1 16]
 [17 14  7 15 18 12  2  8 15 18 19  1 19  6 12  0 13  5 17  8]
 [ 6 19 12 16 10 10 16  3 13  4  7 12  9  0 11  5 14 11  4  1]
 [12  6 11  8 13 19 13 16  2  8 15 14  5  9 18 16  9 10  9 13]
 [ 2  1 17  8 17 12 19 17  3 16  6  7 17 10 12  9 14  5 17  1]
 [ 3  8 12  4  4  4  0  4 13  4 14 12 15 14  5  5  3  7 10  6]
 [ 1 12  8  8  1 13  5 12 18 19 17  0  6  7 14  2 15 13

In [62]:
def sort_matrix(mat, size: tuple):
    diagonals = np.array(sort_diagonals(mat, size), dtype = object)

    current_x = 0
    current_y = 0


    for i in range(size[0]-1, -1, -1):
        y = i
        x = 0
        while y <= size[0]-1 and x <= size[1]-1:
            mat[y][x] = diagonals[current_y][current_x]
            y+=1
            x+=1
            current_x = (current_x + 1) % (len(diagonals[current_y]))
            if current_x == 0: current_y = (current_y + 1) % (len(diagonals) + 1)



    for i in range(1, size[1]):
        y = 0
        x = i
        while y <= size[0]-1 and x <= size[1]-1:
            mat[y][x] = diagonals[current_y][current_x]
            y+=1
            x+=1
            current_x = (current_x + 1) % (len(diagonals[current_y]))
            if current_x == 0: current_y += 1

    return mat
        

In [63]:
a = sample_matrix(size=(20,20))
print(a, '\n\n-----------------\n')

print(sort_matrix(a,size =  (20, 20)), '\n\n')

[[15 18  3 18  1  0  4 17  1  4  2  9  1  4 10  0  7 14  4 19]
 [10 16 15 10 18 10  4  8  1 17  8  6  4  3 13 11 19  1 19 17]
 [ 4  3 15 15 19  4 10  6  5 18 18  0  1  8  0 10 12  1  1 13]
 [13 18  9 13 19  8  4 11  1 16 16  7 13  0  8 11 19  5  2 10]
 [ 3 17  1 14 10 13 14  1  6 15 12 19 12  0  0 16  8  9  1  4]
 [16 16  9  4  4  6  5  8  4 16 11  6 19  2  0  6  8 13 13 19]
 [18 12  1 13  0 14 13  0 16 13 15 18 11  7  7  4  8  5  1  0]
 [ 4  9 11 15 16 17  5 16 19  0  6 11 14  9  9 14 18 10  3  1]
 [ 8 15 16  7  8 15  7  0  3  4 12 17  0  3 19 10 14 16  2 11]
 [16  5  0 13  0  8  6 18  5 18  4 15  6  3 18  2  8 11 17 13]
 [14 13  1  4 18  5  9  6  4 13 18 10 15  7  3 15  8  8 11  5]
 [ 8  9 13  1 13  9  2 18  5  4  7  6 19 15  4  9  1 14 13 17]
 [ 2 15 12 17 10 18 11 13  2 16 10 12 18 14 19  4  1  9 15 12]
 [15  8  2 10 13 10  1 19  6 17 12  8  8 17 10  1 15  1 15  9]
 [ 3  5  3  7  7 16 16 15 14 18  6 10  3 18  1  5  9 12  7  3]
 [15  5 19  6  9 14 10 13 10 17  3 15 17  6  2  6  5 13